name: Generate tag

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          branch: 'release-test'
