name: Generate tag

on:
  push:
    branches:
      - release


jobs:
  build:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '1'

      - name: Bump version and push tag
        uses: 1jGabriel/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: release.*